name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container: cuaesd/aesd-autotest:24-assignment7-buildroot
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
          - name: Cache buildroot downloads and builds
            uses: actions/cache@v4
            with:
              path: |
                buildroot/dl
                buildroot/output/build
              key: ${{ runner.os }}-buildroot-${{ hashFiles('buildroot/Config.in buildroot/package/** .config') }}
              restore-keys: |
                ${{ runner.os }}-buildroot-
          - name: Prepare Buildroot
            run: make -C buildroot olddefconfig
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: Run full test
            env:
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: ./full-test.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
